name: Deploy

on: push
  # workflow_dispatch:


env:
  DAY_OF_WEEK: ""

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create instances
        run: |
            TEST="Hello World"
            echo $TEST
            echo "DAY_OF_WEEK=$TEST" >> $GITHUB_ENV
            

      - name: Print DAY_OF_WEEK
        run: echo "DAY_OF_WEEK is $DAY_OF_WEEK"
