name: Deploy

on: push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get Access Token
        run: echo "TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV

      - name: Test API request
        run: |
          curl -H "Authorization: Bearer $TOKEN" https://www.googleapis.com/auth/cloud-platform
      - name: Install
        run: |
            gcloud -v
            gcloud projects list