name: Deploy

on: push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v1

      - name: Install gcloud
        run: |
            sudo apt update &&  sudo apt upgrade -y
            gcloud -v